version: '3.9'
services:
  redis:
    container_name: voter-api-redis
    image: 'redis/redis-stack:latest'
    ports:
      - '8001:8001'
      - '6379:6379'
  voter-api:
    container_name: np869-voter-api
    depends_on:
      - redis
    image: nisargrajendrakumar/voter-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1080:1080'
